.TH ST 1 st\-VERSION
.SH NAME
st \- simple terminal
.SH SYNOPSIS
.B st
.RB [ \-c
.IR class ]
.RB [ \-f
.IR font ]
.RB [ \-g
.IR geometry ]
.RB [ \-o
.IR file ]
.RB [ \-t 
.IR title ]
.RB [ \-w 
.IR windowid ]
.RB [ \-v ]
.RB [ \-e
.IR command ...]
.SH DESCRIPTION
.B st
is a simple terminal emulator.
.SH OPTIONS
.TP
.BI \-c " class"
defines the window class (default $TERM).
.TP
.BI \-f " font"
defines the
.I font
to use when st is run.
.TP
.BI \-g " geometry"
defines the X11 geometry string, which will fixate the height and width of st. 
.TP
.BI \-o " file"
writes all the I/O to
.I file.
This feature is useful when recording st sessions. A value of "-" means
standard output.
.TP
.BI \-t " title"
defines the window title (default 'st').
.TP
.BI \-w " windowid"
embeds st within the window identified by 
.I windowid
.TP
.B \-v
prints version information to stderr, then exits.
.TP
.BI \-e " program " [ " arguments " "... ]"
st executes
.I program
instead of the shell.  If this is used it
.B must be the last option
on the command line, as in xterm / rxvt.
.SH CUSTOMIZATION
.B st
can be customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR tabbed (1)
.SH BUGS
See the TODO file in the distribution.

